FROM node:18-alpine3.16 AS build
# travailler depuis l'app
WORKDIR /app
# copy front depuis racine
COPY front .

RUN npm install
# build en prod
RUN npm run build


FROM nginx
# creation nginx, copy conf, recuperation executable compiler
COPY docker/front/nginx.conf /etc/nginx/conf.d/default.conf
# vider dossier
RUN rm -rf /usr/share/nginx/html/*
# remplissage avec executable d'avant
COPY --from=build /app/build /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

CMD ["/bin/sh", "-c", "nginx -g \"daemon off;\""]